name: test
run-name: tests for ${{ github.ref }}
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.43
          actions-cache-folder: 'cache-emsdk'
      - uses: actions/cache@v3
        with:
          key: libav-js-dependencies
          path: build/*.tar.*
      - run: make extract
      - run: npm test
